export const PRODUCTS = 'PRODUCTS';
export const PRODUCTS_DESCRIPTIONS = 'PRODUCTS_DESCRIPTIONS';
export const CATEGORIES = 'CATEGORIES';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const IS_FORM_SUBMITTED = 'IS_FORM_SUBMITTED';
export const SALES_INVOICES = 'SALES_INVOICES';
export const IS_OPEN_MODAL = 'IS_OPEN_MODAL';
export const SELECTED_PRODUCTS = 'SELECTED_PRODUCTS';
export const SALE_PRODUCTS = 'SALE_PRODUCTS';
export const MESSAGE_SHOWED = 'MESSAGE_SHOWED';
export const SALE_INVOICE_TO_SHOW = 'SALE_INVOICE_TO_SHOW';
export const SOLD_PRODUCTS = 'SOLD_PRODUCTS';


export const IS_TOKEN_VALID = 'IS_TOKEN_VALID';
export const TOKEN_DOES_NOT_VALID = 'TOKEN_DOES_NOT_VALID';
export const USER_ID_CONTAINER = 'USER_ID_CONTAINER';
export const LOADING = 'LOADING';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_DID_NOT_LOG_IN = 'USER_DID_NOT_LOG_IN';

export const ADD_ORDERS = 'ADD_ORDERS';
export const ORDERS = 'ORDERS';
export const SHOW_ONE_ORDER_DETAILS = 'SHOW_ONE_ORDER_DETAILS';
export const PRODUCTS_LIST = 'PRODUCTS_LIST';
export const ADD_TO_PRODUCTS_LIST = 'ADD_TO_PRODUCTS_LIST';
export const SELECTED_PRODUCTS_LIST_FOR_STORAGE = 'SELECTED_PRODUCTS_LIST_FOR_STORAGE';
export const SELECTED_PRODUCTS_LIST_FOR_PRE_INVOICE = 'SELECTED_PRODUCTS_LIST_FOR_PRE_INVOICE';
export const ADD_TO_STORAGE = 'ADD_TO_STORAGE';
export const ADD_TO_PRE_INVOICE = 'ADD_TO_PRE_INVOICE';
export const PRE_INVOICES = 'PRE_INVOICES';
export const SHOW_ONE_PRE_INVOICE_DETAILS = 'SHOW_ONE_PRE_INVOICE_DETAILS';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ERROR = 'ERROR';
export const USERS = 'USERS';
export const UPDATE_ACCESS = 'UPDATE_ACCESS';
export const CHECK_ORDERS_ACCESS = 'CHECK_ORDERS_ACCESS';
export const CHECK_PRE_INVOICES_ACCESS = 'CHECK_PRE_INVOICES_ACCESS';
export const CHECK_STORAGE_ACCESS = 'CHECK_STORAGE_ACCESS';




